### ISSUE TITLE
Registration form validation

### ISSUE THREAD

**Issue by kutsyk** [Uaman/NextBook#1]
Я вводжу gmail воно пише що неправильний формат. 
![image](https://cloud.githubusercontent.com/assets/6589214/8927588/268c17a8-3521-11e5-82e4-dfc9e38ef319.png)

**Comment by borsch** [comment]
з реджексом проблеми. він не фантан. треба щось краще знайти.
тут помилка з тим що є крапочка vasya.kutsyk. цієї крапочки(по реджексу) не має бути

**Comment by borsch** [comment]
виправив
